# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

extends: default

ignore:
  - data/hipblaslt/

rules:
  line-length: disable
  trailing-spaces: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  empty-lines:
    max-end: 1
  document-start: disable
