#!/usr/bin/env python3
# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Collect license evidence from a built container filesystem."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from email.parser import BytesParser
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlsplit, urlunsplit


DOCUMENT_NAME = re.compile(
    r"(?:^|[-_.])(?:licenses?|licences?|copying|notices?|copyrights?|"
    r"third[-_.]?party(?:[-_.]?notices?)?|patents?)(?=$|[-_.])",
    re.IGNORECASE,
)
LEGAL_DIRECTORIES = {"legal", "licence", "licences", "license", "licenses"}
IGNORED_DIRECTORIES = {
    ".cache",
    ".ccache",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    "__pycache__",
    "artifacts",
    "build",
    "git-mirror",
    "node_modules",
}
NON_DOCUMENT_SUFFIXES = {
    ".a",
    ".c",
    ".cc",
    ".class",
    ".cpp",
    ".dll",
    ".dylib",
    ".h",
    ".hpp",
    ".jar",
    ".o",
    ".obj",
    ".py",
    ".pyc",
    ".pyd",
    ".pyi",
    ".so",
}
LABEL = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Directory to replace with the generated license bundle",
    )
    parser.add_argument(
        "--scan-root",
        action="append",
        default=[],
        metavar="LABEL=PATH",
        help="Recursively collect conventionally named legal documents",
    )
    parser.add_argument(
        "--evidence-root",
        action="append",
        default=[],
        metavar="LABEL=PATH",
        help="Import a complete evidence bundle generated by this collector",
    )
    parser.add_argument(
        "--git-root",
        action="append",
        default=[],
        type=Path,
        help="Discover Git repositories and record their provenance below PATH",
    )
    parser.add_argument(
        "--python-root",
        action="append",
        default=[],
        type=Path,
        help="Inventory Python distributions installed below PATH",
    )
    parser.add_argument(
        "--debian",
        action="store_true",
        help="Inventory dpkg packages and collect Debian copyright files",
    )
    parser.add_argument(
        "--fail-on-missing-git-license",
        action="store_true",
        help="Fail when a Git repository in the required depth has no legal file",
    )
    parser.add_argument(
        "--required-git-depth",
        type=int,
        default=0,
        help="Maximum path depth below a Git root subject to the failure check",
    )
    return parser.parse_args()


def labelled_roots(values: Iterable[str], option: str) -> list[tuple[str, Path]]:
    roots: list[tuple[str, Path]] = []
    labels: set[str] = set()
    for value in values:
        label, separator, raw_path = value.partition("=")
        if not separator or not LABEL.fullmatch(label) or not raw_path:
            raise ValueError(f"invalid {option} {value!r}; expected LABEL=PATH")
        if label in labels:
            raise ValueError(f"duplicate {option} label: {label}")
        path = Path(raw_path).resolve()
        if not path.is_dir():
            raise ValueError(f"{option} is not a directory: {path}")
        labels.add(label)
        roots.append((label, path))
    return roots


def walk_files(root: Path) -> Iterable[Path]:
    for directory, directory_names, file_names in os.walk(root, followlinks=False):
        directory_names[:] = sorted(
            name
            for name in directory_names
            if name not in IGNORED_DIRECTORIES
            and not (Path(directory) / name).is_symlink()
        )
        for file_name in sorted(file_names):
            path = Path(directory) / file_name
            if path.is_file():
                yield path


def is_legal_document(path: Path, root: Path) -> bool:
    relative = path.relative_to(root)
    if path.suffix.lower() in NON_DOCUMENT_SUFFIXES:
        return False
    if DOCUMENT_NAME.search(path.name):
        return True
    return any(part.lower() in LEGAL_DIRECTORIES for part in relative.parts[:-1])


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def copy_file(
    source: Path,
    relative_destination: Path,
    output: Path,
    files: list[dict[str, str]],
) -> str:
    destination = output / "files" / relative_destination
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination, follow_symlinks=True)
    destination.chmod(0o644)
    destination_path = destination.relative_to(output).as_posix()
    files.append(
        {
            "destination": destination_path,
            "sha256": sha256(destination),
            "source": source.as_posix(),
        }
    )
    return destination_path


def collect_scan_roots(
    roots: list[tuple[str, Path]], output: Path, files: list[dict[str, str]]
) -> None:
    for label, root in roots:
        for source in walk_files(root):
            if is_legal_document(source, root):
                copy_file(source, Path(label) / source.relative_to(root), output, files)


def collect_evidence_roots(
    roots: list[tuple[str, Path]], output: Path, files: list[dict[str, str]]
) -> list[dict[str, str]]:
    bundles: list[dict[str, str]] = []
    for label, root in roots:
        manifest = root / "MANIFEST.json"
        if not manifest.is_file():
            raise ValueError(f"evidence root has no MANIFEST.json: {root}")
        manifest_destination = ""
        for source in walk_files(root):
            destination = copy_file(
                source,
                Path("evidence") / label / source.relative_to(root),
                output,
                files,
            )
            if source == manifest:
                manifest_destination = destination
        bundles.append(
            {
                "label": label,
                "manifest": manifest_destination,
                "source": root.as_posix(),
            }
        )
    return bundles


def run_command(arguments: list[str], cwd: Path | None = None) -> tuple[int, str]:
    result = subprocess.run(
        arguments,
        cwd=cwd,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    return result.returncode, result.stdout.strip()


def discover_git_repositories(root: Path) -> list[Path]:
    repositories: list[Path] = []
    for directory, directory_names, file_names in os.walk(root, followlinks=False):
        directory_path = Path(directory)
        if ".git" in directory_names or ".git" in file_names:
            repositories.append(directory_path)
        directory_names[:] = sorted(
            name
            for name in directory_names
            if name not in IGNORED_DIRECTORIES
            and not (directory_path / name).is_symlink()
        )
    return repositories


def redact_url(raw_url: str) -> str:
    try:
        parsed = urlsplit(raw_url)
    except ValueError:
        return raw_url
    if not parsed.hostname or not parsed.username:
        return raw_url
    host = parsed.hostname
    if parsed.port:
        host = f"{host}:{parsed.port}"
    return urlunsplit((parsed.scheme, host, parsed.path, parsed.query, parsed.fragment))


def owning_repository(source: Path, repositories: list[Path]) -> Path | None:
    owners = [repository for repository in repositories if source.is_relative_to(repository)]
    if not owners:
        return None
    return max(owners, key=lambda path: len(path.parts))


def is_repository_legal_file(source: Path, repository: Path) -> bool:
    relative = source.relative_to(repository)
    return len(relative.parts) <= 2 or relative.parts[0].lower() in LEGAL_DIRECTORIES


def repository_is_required(
    repository: Path, git_roots: list[Path], required_depth: int
) -> bool:
    return any(
        repository.is_relative_to(root)
        and len(repository.relative_to(root).parts) <= required_depth
        for root in git_roots
    )


def collect_git_repositories(
    git_roots: list[Path],
    files: list[dict[str, str]],
    required_depth: int,
) -> tuple[list[dict[str, Any]], list[str], list[str]]:
    repositories = sorted(
        {repository for root in git_roots for repository in discover_git_repositories(root)}
    )
    owned_files: dict[Path, list[dict[str, str]]] = {
        repository: [] for repository in repositories
    }
    for file_record in files:
        source = Path(file_record["source"])
        owner = owning_repository(source, repositories)
        if owner is not None:
            owned_files[owner].append(file_record)

    records: list[dict[str, Any]] = []
    warnings: list[str] = []
    missing_required: list[str] = []
    for repository in repositories:
        _, revision = run_command(["git", "rev-parse", "HEAD"], repository)
        _, origin = run_command(["git", "remote", "get-url", "origin"], repository)
        status_code, status = run_command(
            ["git", "status", "--porcelain", "--untracked-files=no"], repository
        )
        legal_files = sorted(
            file_record["destination"]
            for file_record in owned_files[repository]
            if is_repository_legal_file(Path(file_record["source"]), repository)
        )
        if not legal_files:
            message = f"Git repository has no root-level legal document: {repository}"
            warnings.append(message)
            if repository_is_required(repository, git_roots, required_depth):
                missing_required.append(repository.as_posix())
        records.append(
            {
                "legal_files": legal_files,
                "origin": redact_url(origin),
                "path": repository.as_posix(),
                "revision": revision,
                "tracked_files_modified": status_code != 0 or bool(status),
            }
        )
    return records, warnings, missing_required


def metadata_values(metadata: Any, key: str) -> list[str]:
    return [value.strip() for value in metadata.get_all(key, []) if value.strip()]


def collect_python_packages(
    python_roots: list[Path], files: list[dict[str, str]]
) -> tuple[list[dict[str, Any]], list[str]]:
    packages: list[dict[str, Any]] = []
    warnings: list[str] = []
    seen_metadata: set[Path] = set()
    for root in python_roots:
        if not root.is_dir():
            raise ValueError(f"Python root is not a directory: {root}")
        for metadata_path in sorted(root.rglob("*.dist-info/METADATA")):
            if metadata_path in seen_metadata:
                continue
            seen_metadata.add(metadata_path)
            with metadata_path.open("rb") as stream:
                metadata = BytesParser().parse(stream, headersonly=True)
            distribution_directory = metadata_path.parent
            legal_files = sorted(
                record["destination"]
                for record in files
                if Path(record["source"]).is_relative_to(distribution_directory)
            )
            name = metadata.get("Name", distribution_directory.name)
            version = metadata.get("Version", "")
            license_values = metadata_values(metadata, "License")
            license_expressions = metadata_values(metadata, "License-Expression")
            declared_license_files = metadata_values(metadata, "License-File")
            if not legal_files and not license_values and not license_expressions:
                warnings.append(f"Python package has no detected license metadata: {name} {version}")
            packages.append(
                {
                    "home_page": metadata.get("Home-page", ""),
                    "legal_files": legal_files,
                    "license": license_values,
                    "license_expression": license_expressions,
                    "license_file": declared_license_files,
                    "metadata_path": metadata_path.as_posix(),
                    "name": name,
                    "project_url": metadata_values(metadata, "Project-URL"),
                    "version": version,
                }
            )
    packages.sort(key=lambda package: (package["name"].lower(), package["version"]))
    return packages, warnings


def collect_debian_packages(
    output: Path, files: list[dict[str, str]]
) -> tuple[list[dict[str, str]], list[str]]:
    warnings: list[str] = []
    copyright_destinations: dict[str, str] = {}
    documentation_root = Path("/usr/share/doc")
    if documentation_root.is_dir():
        for source in sorted(documentation_root.glob("*/copyright")):
            if source.is_file():
                package_name = source.parent.name
                copyright_destinations[package_name] = copy_file(
                    source,
                    Path("debian") / source.relative_to("/"),
                    output,
                    files,
                )

    common_licenses = Path("/usr/share/common-licenses")
    if common_licenses.is_dir():
        for source in walk_files(common_licenses):
            copy_file(
                source,
                Path("debian") / source.relative_to("/"),
                output,
                files,
            )

    return_code, package_output = run_command(
        [
            "dpkg-query",
            "-W",
            "-f=${binary:Package}\\t${Version}\\t${Architecture}\\t${db:Status-Abbrev}\\n",
        ]
    )
    if return_code != 0:
        return [], ["dpkg-query failed; Debian package inventory is unavailable"]

    packages: list[dict[str, str]] = []
    for line in package_output.splitlines():
        fields = line.split("\t")
        if len(fields) != 4 or not fields[3].startswith("ii"):
            continue
        name, version, architecture, _ = fields
        documentation_name = name.split(":", maxsplit=1)[0]
        packages.append(
            {
                "architecture": architecture,
                "copyright_file": copyright_destinations.get(documentation_name, ""),
                "name": name,
                "version": version,
            }
        )
    packages.sort(key=lambda package: package["name"])
    return packages, warnings


def main() -> int:
    arguments = parse_args()
    if arguments.required_git_depth < 0:
        print("--required-git-depth must be non-negative", file=sys.stderr)
        return 2
    try:
        scan_roots = labelled_roots(arguments.scan_root, "--scan-root")
        evidence_roots = labelled_roots(arguments.evidence_root, "--evidence-root")
        git_roots = [path.resolve() for path in arguments.git_root]
        python_roots = [path.resolve() for path in arguments.python_root]
        for root in git_roots:
            if not root.is_dir():
                raise ValueError(f"Git root is not a directory: {root}")

        output = arguments.output.resolve()
        if output.exists():
            shutil.rmtree(output)
        output.mkdir(parents=True)

        files: list[dict[str, str]] = []
        collect_scan_roots(scan_roots, output, files)
        evidence_bundles = collect_evidence_roots(evidence_roots, output, files)
        repositories, git_warnings, missing_required = collect_git_repositories(
            git_roots, files, arguments.required_git_depth
        )
        python_packages, python_warnings = collect_python_packages(python_roots, files)
        if arguments.debian:
            debian_packages, debian_warnings = collect_debian_packages(output, files)
        else:
            debian_packages, debian_warnings = [], []

        files.sort(key=lambda record: record["destination"])
        manifest = {
            "debian_packages": debian_packages,
            "evidence_bundles": evidence_bundles,
            "files": files,
            "git_repositories": repositories,
            "python_packages": python_packages,
            "scan_roots": [
                {"label": label, "path": path.as_posix()} for label, path in scan_roots
            ],
            "schema_version": 1,
            "warnings": sorted(git_warnings + python_warnings + debian_warnings),
        }
        (output / "MANIFEST.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
    except (OSError, ValueError) as error:
        print(f"license collection failed: {error}", file=sys.stderr)
        return 2

    print(
        f"Collected {len(files)} evidence files, {len(repositories)} Git repositories, "
        f"{len(python_packages)} Python packages, and {len(debian_packages)} Debian packages."
    )
    if missing_required and arguments.fail_on_missing_git_license:
        for repository in missing_required:
            print(f"missing required Git license: {repository}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())