# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

ARG BASE_IMAGE="lmsysorg/sglang:v0.5.17"
FROM ${BASE_IMAGE}

ARG SGL_REPO="https://github.com/avjves/sglang.git"
ARG SGL_COMMIT="feature/combined_perf_1008"

# Optionally reinstall SGL from a custom repo/commit
RUN if [ -n "${SGL_REPO}" ]; then \
        pip uninstall -y sglang && \
        git clone ${SGL_REPO} /app/sglang && \
        cd /app/sglang && \
        if [ -n "${SGL_COMMIT}" ]; then git checkout ${SGL_COMMIT}; fi && \
        pip install --no-cache-dir -e "python[diffusion]"; \
    fi

# Envs
ENV SGLANG_TORCH_COMPILE_MODE="default"
ENV SGLANG_DIFFUSION_DISABLE_SP_PAD_MASK=1

WORKDIR /app
# copy assets
COPY assets/data /app/data
# Include CI
COPY .ci/run.py /app/.ci/run.py
COPY .ci/integrations/sgld/runner.py /app/.ci/runner.py
COPY benchmark_configs/sgld/ /app/.ci/benchmark_configs/
