# Build example image with
#
# docker build -f docker/Dockerfile.base.therock \
#              -t amdsiloai/pytorch-private:ubuntu24.04-rocm7.0.0rc20250820-pytorch2.9-gfx950 \
#              --build-arg GPU_ARCH=gfx950 \
#              --build-arg THEROCK_ROCM_NIGHTLY="20250820" .
#
# when running from repository root.
#

# target GPU
ARG GPU_ARCH="gfx950"
ARG THEROCK_COMMIT="4d69f64"
ARG THEROCK_ROCM_NIGHTLY="20250820"
ARG TRITON_BRANCH="pytorch/rocm7.1_internal_testing"
ARG PYTORCH_BRANCH="triton_kernel_wrap_fix"
ARG PYTORCH_VISION_COMMIT="824e8c8726b65fd9d5abdc9702f81c2b0c4c0dc8"

FROM ubuntu:24.04 AS base
ARG GPU_ARCH
ARG THEROCK_ROCM_NIGHTLY

# install depedencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    libgfortran5 \
    libgl1 \
    libglib2.0-dev \
    ninja-build \
    python3 \
    python3-dev \
    python3-packaging \
    python3-pip \
    python3-venv \
    wget \
    && rm -rf /var/lib/apt/lists/*

# setup environment
WORKDIR /app
RUN python3 -m venv .venv
ENV PATH="/app/.venv/bin:$PATH"
RUN git config --global user.name "TheRock Builder" && \
    git config --global user.email "builder@rocm.ai"

# Install ROCm stack
RUN python -m pip install \
    --no-cache-dir \
    --index-url "https://d2awnip2yjpvqn.cloudfront.net/v2/${GPU_ARCH}-dcgpu/" \
    "rocm[libraries,devel]==7.0.0rc${THEROCK_ROCM_NIGHTLY}"
# Running `rocm-sdk path --root` ensures `/app/.venv/lib/python3.12/site-packages/_rocm_sdk_devel` is populated 
RUN rocm-sdk path --root

FROM base AS build_torch
ARG THEROCK_COMMIT
ARG TRITON_BRANCH
ARG PYTORCH_BRANCH
ARG PYTORCH_VISION_COMMIT

RUN git clone https://github.com/ROCm/TheRock.git \
    && cd /app/TheRock/external-builds/pytorch \
    && git checkout ${THEROCK_COMMIT} \
    && python pytorch_torch_repo.py checkout --gitrepo-origin https://github.com/ROCm/pytorch.git --repo-hashtag ${PYTORCH_BRANCH} \
    && python pytorch_triton_repo.py checkout --gitrepo-origin https://github.com/ROCm/triton.git --repo-hashtag ${TRITON_BRANCH} \
    && python pytorch_vision_repo.py checkout --gitrepo-origin https://github.com/pytorch/vision.git --repo-hashtag ${PYTORCH_VISION_COMMIT} \
    && python build_prod_wheels.py build --output-dir /app/install

FROM base AS final
COPY --from=build_torch /app/install/*.whl /app/install/
RUN python -m pip install \
    --no-cache-dir \
    /app/install/*.whl
COPY docker/libkineto.conf /app/libkineto.conf
ENV PATH="/app/.venv/lib/python3.12/site-packages/_rocm_sdk_devel/bin:$PATH" \
    ROCM_HOME=/app/.venv/lib/python3.12/site-packages/_rocm_sdk_devel \
    LD_LIBRARY_PATH=/app/.venv/lib/python3.12/site-packages/_rocm_sdk_devel/lib \
    TRITON_HIP_LLD_PATH=/app/.venv/lib/python3.12/site-packages/_rocm_sdk_core/lib/llvm/bin/ld.lld \
    KINETO_CONFIG="/app/libkineto.conf"
