# Build example image with
#
# docker build -f docker/Dockerfile.ci \
#              -t amdsiloai/pytorch-xdit:latest .
#
# when running from repository root.
#

# core image arguments
ARG BASE_IMAGE="ubuntu:24.04"
ARG PYTHON_VERSION="default"
ARG THEROCK_COMMIT="1728a81e5cd97ff366dc04e2517cf53774d53501"
# Set ROCM_LIBRARIES_COMMIT_OVERRIDE to force to use a specific commit of rocm-libraries monorepo instead of the one pinned in TheRock.
# This is useful for example for testing a feature not yet in the main branch of rocm-libraries or a commit not available via TheRock.
ARG ROCM_LIBRARIES_COMMIT_OVERRIDE=""
ARG TRITON_COMMIT="a272dfa85e20c6c167a1ec0fab48f7f9f4fd47c4"
ARG PYTORCH_COMMIT="91be249cee02ddd0b31f98438ca1b82d10e13dc4"
ARG PYTORCH_VISION_COMMIT="b919bd0c56abbb3c5ca056a3a458af9fd1cabf52"
ARG PYTORCH_AUDIO_COMMIT="e3c6ee2b6588b7cd27a84182de74bf12fe043831"
ARG PYTORCH_CODEC_COMMIT="6df7fc8e81c9509e86833ca48695609c583e2953"
# deps image arguments
ARG AITER_COMMIT="42ae0ad0fa39504a6b44235174fbcfb20e49ae38"
ARG LONGCONTEXTATTENTION_COMMIT="631bdfd"
ARG DIFFUSERS_COMMIT="a3dcd9"
ARG ACCELERATE_COMMIT="b7f2212"
ARG XDIT_COMMIT="635fc29"
ARG AO_COMMIT="8b72284"
ARG ARBITER_COMMIT="252b0301d072f9d6ea895e32f6898fed951cf295"

FROM ${BASE_IMAGE} AS build_python
ARG PYTHON_VERSION
ARG DEBIAN_FRONTEND=noninteractive
RUN if [ "${PYTHON_VERSION}" = "default" ]; then \
        mkdir -p /opt/python/usr; \
    else \
        # install python3 (optional) dependencies on Ubuntu 24.04
        echo "deb-src http://archive.ubuntu.com/ubuntu noble main universe" \
          >> /etc/apt/sources.list; \
        apt-get update -qq && apt-get build-dep python3 -y && apt-get install --no-install-recommends -y \
            build-essential \
            ca-certificates \
            gdb \
            lcov \
            pkg-config \
            libbz2-dev \
            # unclear if needed
            libexpat1-dev \
            libffi-dev \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libncurses5-dev \
            libreadline6-dev \
            libsqlite3-dev \
            libssl-dev \
            lzma \
            lzma-dev \
            tk-dev \
            uuid-dev \
            zlib1g-dev \
            # do not install on Ubuntu 24.04 
#            libmpdec-dev \
            libzstd-dev \
            inetutils-inetd \
            # unclear if needed
            systemtap-sdt-dev \
            wget && \
            update-ca-certificates && \
            rm -rf /var/lib/apt/lists/*; \
        # build prespecified Python version
        wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz; \
        tar -xf Python-${PYTHON_VERSION}.tgz; \
        cd Python-${PYTHON_VERSION}; \
        ./configure \
            --prefix=/usr \
            --enable-shared \
            --enable-optimizations \
            --enable-ipv6 \
            --with-system-ffi \
            # unclear if needed
            --with-system-expat \
            --with-dbmliborder=bdb:gdbm \
            --enable-loadable-sqlite-extensions \
            --with-dtrace; \
        make -j$(nproc); \
        make install DESTDIR=/opt/python; \
    fi

FROM ${BASE_IMAGE} AS base
ARG PYTHON_VERSION
ARG DEBIAN_FRONTEND=noninteractive

# install depedencies
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    automake \
    bison \
    build-essential \
    ca-certificates \
    cmake \
    flex \
    freeglut3-dev \
    gfortran \
    git \
    libgfortran5 \
    libgl1 \
    libgl1-mesa-dev \
    libglib2.0-dev \
    libglu1-mesa-dev \
    libopenblas-dev \
    libtool \
    ninja-build \
    patchelf \
    texinfo \
    wget \
    xxd && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# install python3
COPY --from=build_python /opt/python/usr /usr
RUN if [ "${PYTHON_VERSION}" = "default" ]; then \
        # install system Python
        apt-get update -qq && apt-get install --no-install-recommends -y \
            python3 \
            python3-dev \
            python3-packaging \
            python3-pip \
            python3-venv && \
            rm -rf /var/lib/apt/lists/*; \
    else \
        # install Python optional runtime dependencies
        apt-get update -qq && apt-get install -y --no-install-recommends \
            ca-certificates \
            # from libbz2-dev
            libbz2-1.0 \
            # from libc6-dev
            libc6 \
            # from libffi-dev
            libffi8 \
            # from libgdbm-dev
            libgdbm6t64 \
            # from libgdbm-dev
            libgdbm-compat4t64 \
            # from liblzma-dev
            liblzma5 \
            # from libreadline6-dev
            libreadline8 \
            # from libsqlite3-dev
            libsqlite3-0 \
            # from libssl-dev
            libssl3t64 \
            # from tk-dev
            tk \
            # from uuid-dev
            libuuid1 \
            # from zlib1g-dev
            zlib1g \
            # from libzstd-dev
            libzstd1 \
            # rest are more unclear dependencies
            libdb5.3 \
            libexpat1 \
            libgdbm6 \
            libncurses6 \
            libtirpc3 \
            uuid-runtime && \
            rm -rf /var/lib/apt/lists/*; \
        # setup prespecified Python version
        PYTHON_MINOR="$(echo "$PYTHON_VERSION" | awk -F. '{print $1"."$2}')"; \
        ln -sf /usr/bin/python${PYTHON_MINOR} /usr/bin/python3; \
        ln -sf /usr/bin/pip${PYTHON_MINOR} /usr/bin/pip3; \
        python3 -m ensurepip --upgrade; \
    fi

# setup environment
RUN python3 -m venv venv
ENV PATH="/venv/bin:$PATH"
RUN pip install --no-cache-dir --upgrade pip packaging setuptools wheel

FROM base AS setup_therock
ARG THEROCK_COMMIT
ARG ROCM_LIBRARIES_COMMIT_OVERRIDE

WORKDIR /app
RUN git clone https://github.com/ROCm/TheRock.git && \
    cd TheRock && \
    git reset --hard ${THEROCK_COMMIT} && \
    if [ -n "$ROCM_LIBRARIES_COMMIT_OVERRIDE" ]; then \
        echo "Force updating rocm-libraries commit to ${ROCM_LIBRARIES_COMMIT_OVERRIDE}" && \
        git update-index --cacheinfo 160000,${ROCM_LIBRARIES_COMMIT_OVERRIDE},rocm-libraries ; \
    fi

FROM base AS build_rocm
COPY --from=setup_therock /app/TheRock /app/TheRock
WORKDIR /app/TheRock
# if dvc is available, fetch_source.py uses it to fetch large files - install it along with other requirements.
RUN pip install --no-cache-dir dvc[s3] && \
    pip install -r requirements.txt && \
    python build_tools/fetch_sources.py
RUN cmake -S /app/TheRock -B /app/TheRock/build -GNinja . \
    -DTHEROCK_AMDGPU_FAMILIES="gfx94X-dcgpu;gfx950-dcgpu" \
    -DTHEROCK_BUNDLE_SYSDEPS=ON -DTHEROCK_AMDGPU_DIST_BUNDLE_NAME="gfx94X_gfx950_bundle" \
    -DCMAKE_INSTALL_PREFIX=/opt/rocm && \
    cmake --build /app/TheRock/build && \
    cmake --install /app/TheRock/build
# FIXME: the next line is a hack to get missing `hip` directory in the installation.
#       This is fixed upstream by https://github.com/ROCm/rocm-systems/pull/2232
#       the hack should be removed when the fix is part of rocm-systems submodule
#       commit of TheRock.
RUN cp -R /app/TheRock/rocm-systems/projects/rocprofiler-compute/src/hip /opt/rocm/libexec/rocprofiler-compute/

FROM base AS rocm_only
COPY --from=build_rocm /opt/rocm /opt/rocm
# Install amdsmi Python module
RUN cd /opt/rocm/share/amd_smi && \
    pip install --no-cache-dir .
RUN echo "/opt/rocm/lib" > /etc/ld.so.conf.d/rocm.conf && \
    echo "/opt/rocm/lib/rocm_sysdeps/lib/" > /etc/ld.so.conf.d/rocm_sysdeps.conf && \
    ldconfig
ENV PATH="/opt/rocm/bin:/opt/rocm/libexec/rocprofiler-compute:$PATH" \
    ROCM_HOME=/opt/rocm \
    ROCM_PATH=/opt/rocm \
    HIP_DEVICE_LIB_PATH=/opt/rocm/lib/llvm/amdgcn/bitcode

FROM rocm_only AS build_torch_stack
ARG TRITON_COMMIT
ARG PYTORCH_COMMIT
ARG PYTORCH_VISION_COMMIT
ARG PYTORCH_AUDIO_COMMIT
ARG PYTORCH_CODEC_COMMIT
COPY --from=setup_therock /app/TheRock /app/TheRock

# needed for HIPIFY commits created by the build process
RUN git config --global user.name "TheRock Builder" && \
    git config --global user.email "builder@rocm.ai"

# fetch sources
WORKDIR /app/TheRock/external-builds/pytorch
RUN pip install -r /app/TheRock/requirements.txt && \
    python pytorch_torch_repo.py checkout --gitrepo-origin https://github.com/ROCm/pytorch.git --repo-hashtag ${PYTORCH_COMMIT} && \
    python pytorch_triton_repo.py checkout --gitrepo-origin https://github.com/ROCm/triton.git --repo-hashtag ${TRITON_COMMIT} && \
    python pytorch_vision_repo.py checkout --gitrepo-origin https://github.com/pytorch/vision.git --repo-hashtag ${PYTORCH_VISION_COMMIT} && \
    python pytorch_audio_repo.py checkout --gitrepo-origin https://github.com/pytorch/audio.git --repo-hashtag ${PYTORCH_AUDIO_COMMIT}
# fetch torchcodec - TODO: after merging https://github.com/ROCm/TheRock/pull/2590 switch to using the functionality there
RUN git clone https://github.com/meta-pytorch/torchcodec.git pytorch_codec && \
    cd pytorch_codec && \
    git reset --hard ${PYTORCH_CODEC_COMMIT}
RUN mkdir /install
# install triton
RUN cd triton && \
    pip install -r python/requirements.txt && \
    pip wheel . --wheel-dir dist/ && \
    pip install dist/*.whl && \
    cp dist/*.whl /install
# install pytorch
RUN cd pytorch && \
    pip install -r requirements.txt && \
    USE_KINETO=ON USE_GLOO=ON USE_ROCM=ON USE_CUDA=OFF USE_MPI=OFF \
    USE_MEM_EFF_ATTENTION=ON USE_FLASH_ATTENTION=ON USE_ROCM_CK_SDPA=ON \
    PYTORCH_ROCM_ARCH="gfx942;gfx950" \
    CXXFLAGS="-I${ROCM_HOME}/include/roctracer -I${ROCM_HOME}/lib/rocm_sysdeps/include" \
    LDFLAGS="-L${ROCM_HOME}/lib/rocm_sysdeps/lib" \
    PKG_CONFIG_PATH="${ROCM_HOME}/lib/rocm_sysdeps/lib/pkgconfig" \
    python setup.py bdist_wheel && \
    pip install dist/*.whl && \
    cp dist/*.whl /install
# install vision
RUN cd pytorch_vision && \
    FORCE_CUDA=1 TORCHVISION_USE_NVJPEG=0 TORCHVISION_USE_VIDEO_CODEC=0 \
    python setup.py bdist_wheel && \
    pip install dist/*.whl && \
    cp dist/*.whl /install
# install audio
RUN cd pytorch_audio && \
    PYTORCH_ROCM_ARCH="gfx942;gfx950" USE_ROCM=1 USE_CUDA=0 USE_FFMPEG=1 USE_OPENMP=1 BUILD_SOX=0 \
    python setup.py bdist_wheel && \
    pip install dist/*.whl && \
    cp dist/*.whl /install
# install torchcodec
RUN pip install --no-cache-dir pybind11 pybind11[global] && \
    cd pytorch_codec && \
    PYTORCH_ROCM_ARCH="gfx942;gfx950" ENABLE_CUDA=0 TORCHCODEC_DISABLE_COMPILE_WARNING_AS_ERROR=1 BUILD_AGAINST_ALL_FFMPEG_FROM_S3=1 \
    python -m build --wheel -vvv --no-isolation -o dist && \
    pip install dist/*.whl && \
    cp dist/*.whl /install

FROM ubuntu:24.04 AS ffmpeg_builder
# Reference: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
# Install build depedencies, server use only
RUN apt-get update -qq && apt-get -y install --no-install-recommends \
    autoconf \
    automake \
    build-essential \
    ca-certificates \
    cmake \
    git-core \
    libaom-dev \
    libass-dev \
    libdav1d-dev \
    libfreetype6-dev \
    libgnutls28-dev \
    libmp3lame-dev \
    libtool \
    libunistring-dev \
    libvorbis-dev \
    meson \
    ninja-build \
    pkg-config \
    texinfo \
    wget \
    yasm \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# See https://ffmpeg.org/releases/ for valid choices of FFMPEG_VERSION
ARG FFMPEG_VERSION="7.1.3"
ENV FFMPEG_BUILD_DIR=/ffmpeg/build
ENV FFMPEG_SRC_DIR=/ffmpeg/src
ENV FFMPEG_BIN_DIR=/ffmpeg/bin
RUN mkdir -p ${FFMPEG_BUILD_DIR} ${FFMPEG_SRC_DIR}
WORKDIR ${FFMPEG_SRC_DIR}
# Never set --enable-gpl or --enagle-nonfree to maintain non-GPL license compliance!
RUN wget -O ffmpeg-${FFMPEG_VERSION}.tar.bz2 https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
    tar xjvf ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
    cd ffmpeg-${FFMPEG_VERSION} && \
    PATH="$FFMPEG_BIN_DIR:$PATH" PKG_CONFIG_PATH="$FFMPEG_BUILD_DIR/lib/pkgconfig" ./configure \
    --prefix="$FFMPEG_BUILD_DIR" \
    --pkg-config-flags="--static" \
    --extra-cflags="-I$FFMPEG_BUILD_DIR/include" \
    --extra-ldflags="-L$FFMPEG_BUILD_DIR/lib" \
    --extra-libs="-lpthread -lm" \
    --ld="g++" \
    --bindir="$FFMPEG_BIN_DIR" \
    --enable-gnutls \
    --enable-libaom \
    --enable-libass \
    --enable-libdav1d \
    --enable-libfreetype \
    --enable-libmp3lame \
    --enable-libvorbis \
    --enable-shared && \
    PATH="$FFMPEG_BIN_DIR:$PATH" make -j$(($(nproc)-1)) && \
    make install && \
    hash -r

FROM base AS install_torch_stack
COPY --from=build_torch_stack /install/*.whl /install/
RUN python -m pip install \
    --no-cache-dir \
    /install/*.whl

FROM rocm_only AS core
COPY --from=install_torch_stack /venv /venv
# torchcodec: install FFmpeg and runtime dependencies
RUN apt-get update -qq && apt-get -y install --no-install-recommends \
  libaom3 \
  libass9 \
  libdav1d7 \
  libfreetype6 \
  libgnutls30 \
  libmp3lame0 \
  libvorbis0a \
  libvorbisenc2 \
  && rm -rf /var/lib/apt/lists/*

# Copy built FFmpeg artifacts from the builder stage
COPY --from=ffmpeg_builder /ffmpeg/bin /usr/local/bin
COPY --from=ffmpeg_builder /ffmpeg/build/lib /usr/local/lib
COPY --from=ffmpeg_builder /ffmpeg/build/include /usr/local/include
COPY --from=ffmpeg_builder /ffmpeg/build/share /usr/local/share

# Update library cache
RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/ffmpeg.conf && \
    ldconfig

COPY docker/libkineto.conf /config/libkineto.conf
ENV TRITON_HIP_LLD_PATH=/opt/rocm/lib/llvm/bin/ld.lld \
    KINETO_CONFIG="/config/libkineto.conf"

FROM core AS deps
ARG AITER_COMMIT
ARG LONGCONTEXTATTENTION_COMMIT
ARG DIFFUSERS_COMMIT
ARG ACCELERATE_COMMIT
ARG XDIT_COMMIT
ARG AO_COMMIT
ARG ARBITER_COMMIT

# setup
WORKDIR /app/external
COPY ./src/patches /patches
# install aiter
RUN pip install pandas
RUN git clone https://github.com/ROCm/aiter.git && \
    cd aiter && \
    git reset --hard ${AITER_COMMIT} && \
    git submodule update --init --recursive && \
    pip install -e .
# install yunchang
RUN git clone https://github.com/feifeibear/long-context-attention.git && \
    cd long-context-attention && \
    git reset --hard ${LONGCONTEXTATTENTION_COMMIT} && \
    git apply /patches/yunchang_aiter_round_mode.patch && \
    pip install -e .
# install diffusers
# final rm step is needed presently to pass a release process image scan
RUN git clone https://github.com/huggingface/diffusers.git && \
    cd diffusers && \
    git reset --hard ${DIFFUSERS_COMMIT} && \
    pip install -e ".[torch]" && \
    rm scripts/convert_vq_diffusion_to_diffusers.py
# install accelerate
RUN git clone https://github.com/huggingface/accelerate.git && \
    cd accelerate && \
    git reset --hard ${ACCELERATE_COMMIT} && \
    pip install -e .
# install torchao
RUN git clone https://github.com/pytorch/ao.git && \
    cd ao && \
    git reset --hard ${AO_COMMIT} && \
    git apply /patches/ao.patch && \
    pip install -e . --no-build-isolation
# install arbiter
RUN git clone https://github.com/fal-ai/arbiter.git && \
    cd arbiter && \
    git reset --hard ${ARBITER_COMMIT} && \
    # too strict torch version, drop dependency
    sed -i '/numpy/d' pyproject.toml && \
    # the requested pyiqa version depends on transformers==4.37.2 which we cannot use
    sed -i '/pyiqa/d' pyproject.toml && \
    # numba dependency is not used
    sed -i '/numba/d' pyproject.toml && \
    # facexlib is not used
    sed -i '/facexlib/d' pyproject.toml && \
    # drop llvmlite
    sed -i '/llvmlite/d' pyproject.toml && \
    # to be sure, pin numpy and transformers to their current versions
    pip freeze | grep -E 'numpy|transformers' > constraints.txt && \
    pip install --no-cache-dir -c constraints.txt -e .
# install xfuser
WORKDIR /app
RUN git clone https://github.com/xdit-project/xDiT.git && \
    cd xDiT && \
    git reset --hard ${XDIT_COMMIT} && \
    pip freeze | grep numpy > constraints.txt && \
    pip install -c constraints.txt -e .
# rocprofiler-compute runtime deps
RUN pip install --no-cache-dir -r ${ROCM_PATH}/libexec/rocprofiler-compute/requirements.txt
# hotfix: until diffusers installs ftfy
RUN pip install ftfy
# hotfix: transformers<5.0.0 required for good output quality
RUN pip uninstall -y transformers && pip install --no-cache-dir "transformers==4.57.6"
# hotfix: transformers needs protobuf
RUN pip install --no-cache-dir "protobuf==6.33.5"
# cleanup
RUN rm -fr /patches

FROM core AS final
# by copying from the deps stage we leave behind all cache and temporary files created during installation
COPY --from=deps /venv /venv
COPY --from=deps /app /app

WORKDIR /app
# copy assets
COPY src/flux/cat.png /app/data/flux_cat.png
COPY src/wan_xdit/assets/i2v_input.JPG /app/data/wan_input.jpg
# copy instructions and CI prerequisites
COPY docs/pytorch-xdit/README.md /app/README.md
COPY .ci/run.py /app/.ci/run.py
COPY benchmark_configs/ /app/.ci/benchmark_configs/
COPY .ci/quality_check.py /app/.ci/quality_check.py
# use shared MIOpen databases
COPY ./data/miopen/userdb /miopen_userdb
ENV MIOPEN_USER_DB_PATH="/miopen_userdb"
# add quality references of workloads
ADD references/ /app/references/
