# Build example image with
#
# docker build -f docker/Dockerfile.ci \
#              -t amdsiloai/pytorch-xdit:latest .
#
# when running from repository root.
#

# core image arguments
ARG THEROCK_COMMIT="1728a81e5cd97ff366dc04e2517cf53774d53501"
# Set ROCM_LIBRARIES_COMMIT_OVERRIDE to force to use a specific commit of rocm-libraries monorepo instead of the one pinned in TheRock.
# This is useful for example for testing a feature not yet in the main branch of rocm-libraries or a commit not available via TheRock.
ARG ROCM_LIBRARIES_COMMIT_OVERRIDE=""
ARG TRITON_COMMIT="a272dfa85e20c6c167a1ec0fab48f7f9f4fd47c4"
ARG PYTORCH_COMMIT="91be249cee02ddd0b31f98438ca1b82d10e13dc4"
ARG PYTORCH_VISION_COMMIT="b919bd0c56abbb3c5ca056a3a458af9fd1cabf52"
# deps image arguments
ARG AITER_COMMIT="de14bec0ca5a9de94e10f5cad4dc1541ac558689"
ARG LONGCONTEXTATTENTION_COMMIT="2c9b712"
ARG DIFFUSERS_COMMIT="a1f36ee"
ARG ACCELERATE_COMMIT="b521400"
ARG XDIT_COMMIT="7ed13e9bd2f90a563439afbd305330857f7380bf"
ARG AO_COMMIT="8b72284"
ARG ARBITER_COMMIT="252b0301d072f9d6ea895e32f6898fed951cf295"

FROM ubuntu:24.04 AS base

# install depedencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    automake \
    bison \
    build-essential \
    cmake \
    flex \
    freeglut3-dev \
    gfortran \
    git \
    libgfortran5 \
    libgl1 \
    libgl1-mesa-dev \
    libglib2.0-dev \
    libglu1-mesa-dev \
    libtool \
    ninja-build \
    patchelf \
    python3 \
    python3-dev \
    python3-packaging \
    python3-pip \
    python3-venv \
    texinfo \
    wget \
    xxd \
    && rm -rf /var/lib/apt/lists/*

# setup environment
RUN python3 -m venv venv
ENV PATH="/venv/bin:$PATH"

FROM base AS setup_therock
ARG THEROCK_COMMIT
ARG ROCM_LIBRARIES_COMMIT_OVERRIDE

WORKDIR /app
RUN git clone https://github.com/ROCm/TheRock.git && \
    cd TheRock && \
    git reset --hard ${THEROCK_COMMIT} && \
    if [ -n "$ROCM_LIBRARIES_COMMIT_OVERRIDE" ]; then \
        echo "Force updating rocm-libraries commit to ${ROCM_LIBRARIES_COMMIT_OVERRIDE}" && \
        git update-index --cacheinfo 160000,${ROCM_LIBRARIES_COMMIT_OVERRIDE},rocm-libraries ; \
    fi

FROM base AS build_rocm
COPY --from=setup_therock /app/TheRock /app/TheRock
WORKDIR /app/TheRock
# if dvc is available, fetch_source.py uses it to fetch large files - install it along with other requirements.
RUN pip install --no-cache-dir dvc[s3] && \
    pip install -r requirements.txt && \
    python build_tools/fetch_sources.py
RUN cmake -S /app/TheRock -B /app/TheRock/build -GNinja . \
    -DTHEROCK_AMDGPU_FAMILIES="gfx94X-dcgpu;gfx950-dcgpu" \
    -DTHEROCK_BUNDLE_SYSDEPS=ON -DTHEROCK_AMDGPU_DIST_BUNDLE_NAME="gfx94X_gfx950_bundle" \
    -DCMAKE_INSTALL_PREFIX=/opt/rocm && \
    cmake --build /app/TheRock/build && \
    cmake --install /app/TheRock/build
# FIXME: the next line is a hack to get missing `hip` directory in the installation.
#       This is fixed upstream by https://github.com/ROCm/rocm-systems/pull/2232 
#       the hack should be removed when the fix is part of rocm-systems submodule 
#       commit of TheRock.
RUN cp -R /app/TheRock/rocm-systems/projects/rocprofiler-compute/src/hip /opt/rocm/libexec/rocprofiler-compute/

FROM base AS rocm_only
COPY --from=build_rocm /opt/rocm /opt/rocm
RUN echo "/opt/rocm/lib" > /etc/ld.so.conf.d/rocm.conf && \
    echo "/opt/rocm/lib/rocm_sysdeps/lib/" > /etc/ld.so.conf.d/rocm_sysdeps.conf && \
    ldconfig
ENV PATH="/opt/rocm/bin:/opt/rocm/libexec/rocprofiler-compute:$PATH" \
    ROCM_HOME=/opt/rocm \
    ROCM_PATH=/opt/rocm \
    HIP_DEVICE_LIB_PATH=/opt/rocm/lib/llvm/amdgcn/bitcode

FROM rocm_only AS build_torch_stack
ARG TRITON_COMMIT
ARG PYTORCH_COMMIT
ARG PYTORCH_VISION_COMMIT
COPY --from=setup_therock /app/TheRock /app/TheRock

# needed for HIPIFY commits created by the build process
RUN git config --global user.name "TheRock Builder" && \
    git config --global user.email "builder@rocm.ai"

# fetch sources
WORKDIR /app/TheRock/external-builds/pytorch
RUN pip install -r /app/TheRock/requirements.txt && \
    python pytorch_torch_repo.py checkout --gitrepo-origin https://github.com/ROCm/pytorch.git --repo-hashtag ${PYTORCH_COMMIT} && \
    python pytorch_triton_repo.py checkout --gitrepo-origin https://github.com/ROCm/triton.git --repo-hashtag ${TRITON_COMMIT} && \
    python pytorch_vision_repo.py checkout --gitrepo-origin https://github.com/pytorch/vision.git --repo-hashtag ${PYTORCH_VISION_COMMIT}
RUN mkdir /install
# install triton
RUN cd triton && \
    pip install -r python/requirements.txt && \
    pip wheel . --wheel-dir dist/ && \
    pip install dist/*.whl && \
    cp dist/*.whl /install
# install pytorch
RUN cd pytorch && \
    pip install -r requirements.txt && \
    USE_KINETO=ON USE_GLOO=ON USE_ROCM=ON USE_CUDA=OFF USE_MPI=OFF \
    USE_MEM_EFF_ATTENTION=ON USE_FLASH_ATTENTION=ON USE_ROCM_CK_SDPA=ON \
    PYTORCH_ROCM_ARCH="gfx942;gfx950" \
    CXXFLAGS="-I${ROCM_HOME}/include/roctracer -I${ROCM_HOME}/lib/rocm_sysdeps/include" \
    LDFLAGS="-L${ROCM_HOME}/lib/rocm_sysdeps/lib" \
    PKG_CONFIG_PATH="${ROCM_HOME}/lib/rocm_sysdeps/lib/pkgconfig" \
    python setup.py bdist_wheel && \
    pip install dist/*.whl && \
    cp dist/*.whl /install
# install vision
RUN cd pytorch_vision && \
    FORCE_CUDA=1 TORCHVISION_USE_NVJPEG=0 TORCHVISION_USE_VIDEO_CODEC=0 \
    python setup.py bdist_wheel && \
    pip install dist/*.whl && \
    cp dist/*.whl /install

FROM base AS install_torch_stack
COPY --from=build_torch_stack /install/*.whl /install/
RUN python -m pip install \
    --no-cache-dir \
    /install/*.whl

FROM rocm_only AS core
COPY --from=install_torch_stack /venv /venv
COPY docker/libkineto.conf /config/libkineto.conf
ENV TRITON_HIP_LLD_PATH=/opt/rocm/lib/llvm/bin/ld.lld \
    KINETO_CONFIG="/config/libkineto.conf"

FROM core AS private-deps

WORKDIR /app/external
# build opt_groupnorm
COPY src/opt_groupnorm opt_groupnorm/
RUN pip install setuptools && \
    cd opt_groupnorm && \
    MAX_JOBS=${MAX_JOBS} pip wheel --no-build-isolation . --wheel-dir dist/

FROM core AS deps
ARG AITER_COMMIT
ARG LONGCONTEXTATTENTION_COMMIT
ARG DIFFUSERS_COMMIT
ARG ACCELERATE_COMMIT
ARG XDIT_COMMIT
ARG AO_COMMIT
ARG ARBITER_COMMIT

# setup
WORKDIR /app/external
COPY ./src/patches /patches
# install opt_groupnorm
COPY --from=private-deps /app/external/opt_groupnorm/dist/*.whl /install/opt_groupnorm/
RUN pip install /install/opt_groupnorm/*.whl
# install aiter
RUN pip install pandas
RUN git clone https://github.com/ROCm/aiter.git && \
    cd aiter && \
    git reset --hard ${AITER_COMMIT} && \
    git submodule update --init --recursive && \
    python setup.py develop
# install yunchang
RUN git clone https://github.com/feifeibear/long-context-attention.git && \
    cd long-context-attention && \
    git reset --hard ${LONGCONTEXTATTENTION_COMMIT} && \
    git apply /patches/yunchang_aiter_round_mode.patch && \
    pip install -e .
# install diffusers
# final rm step is needed presently to pass a release process image scan
RUN git clone https://github.com/huggingface/diffusers.git && \
    cd diffusers && \
    git reset --hard ${DIFFUSERS_COMMIT} && \
    pip install -e ".[torch]" && \
    rm scripts/convert_vq_diffusion_to_diffusers.py
# install accelerate
RUN git clone https://github.com/huggingface/accelerate.git && \
    cd accelerate && \
    git reset --hard ${ACCELERATE_COMMIT} && \
    pip install -e .
# install xfuser
RUN git clone https://github.com/xdit-project/xDiT.git && \
    cd xDiT && \
    git reset --hard ${XDIT_COMMIT} && \
    pip freeze | grep numpy > constraints.txt && \
    git apply /patches/xfuser_joint_attn_processor2_0_usp.patch && \
    git apply /patches/xfuser_attention_backend.patch && \
    git apply /patches/xfuser_runtime_state.patch && \
    git apply /patches/xfuser_usp.patch && \
    pip install -c constraints.txt -e .
# install torchao
RUN git clone https://github.com/pytorch/ao.git && \
    cd ao && \
    git reset --hard ${AO_COMMIT} && \
    git apply /patches/ao.patch && \
    pip install -e . --no-build-isolation
# install arbiter
RUN git clone https://github.com/fal-ai/arbiter.git && \
    cd arbiter && \
    git reset --hard ${ARBITER_COMMIT} && \
    # too strict torch version, drop dependency
    sed -i '/numpy/d' pyproject.toml && \
    # the requested pyiqa version depends on transformers==4.37.2 which we cannot use
    sed -i '/pyiqa/d' pyproject.toml && \
    # numba dependency is not used
    sed -i '/numba/d' pyproject.toml && \
    # facexlib is not used
    sed -i '/facexlib/d' pyproject.toml && \
    # drop llvmlite
    sed -i '/llvmlite/d' pyproject.toml && \
    # to be sure, pin numpy and transformers to their current versions
    pip freeze | grep -E 'numpy|transformers' > constraints.txt && \
    pip install --no-cache-dir -c constraints.txt -e .
# rocprofiler-compute runtime deps
RUN pip install --no-cache-dir -r ${ROCM_PATH}/libexec/rocprofiler-compute/requirements.txt
# cleanup
RUN rm -fr /patches

FROM deps AS hunyuanvideo

WORKDIR /app/Hunyuanvideo
COPY src/xDiT/ci/README_huvideo.md /app/Hunyuanvideo/RUN.md
COPY src/xDiT/ci/video_descriptions.csv /app/Hunyuanvideo/video_descriptions.csv
COPY src/xDiT/ci/huvideo_utils.py /app/Hunyuanvideo/huvideo_utils.py
COPY src/xDiT/ci/hunyuan_video_usp_example_custom.py /app/Hunyuanvideo/run.py

FROM deps AS flux
WORKDIR /app/Flux
COPY src/flux/ci/README.md /app/Flux/RUN.md
COPY src/flux/flux_utils.py /app/Flux/flux_utils.py
COPY src/flux/flux_example.py /app/Flux/run.py
COPY src/flux/flux_usp_example.py /app/Flux/run_usp.py
COPY src/flux/requirements.txt /app/Flux/requirements.txt
COPY src/flux/cat.png /app/Flux/cat.png

FROM deps AS stablediffusion3.5
WORKDIR /app/StableDiffusion3.5
COPY src/SD_3_5/ci/README.md /app/StableDiffusion3.5/RUN.md
COPY src/SD_3_5/scripts/sd3_utils.py /app/StableDiffusion3.5/sd3_utils.py
COPY src/SD_3_5/scripts/sd3_example.py /app/StableDiffusion3.5/run.py

FROM deps AS wan
WORKDIR /app/Wan
COPY src/wan_xdit/ci/README.md /app/Wan/RUN.md
COPY src/wan_xdit/wan_utils.py /app/Wan/wan_utils.py
COPY src/wan_xdit/wan_example.py /app/Wan/run.py
COPY src/wan_xdit/assets/i2v_input.JPG /app/Wan/i2v_input.JPG
COPY src/wan_xdit/requirements.txt /app/Wan/requirements.txt

FROM deps AS z_image
WORKDIR /app/Z-Image
COPY src/z_image/ci/README.md /app/Z-Image/RUN.md
COPY src/z_image/z_image_utils.py /app/Z-Image/z_image_utils.py
COPY src/z_image/z_image_example.py /app/Z-Image/run.py

FROM core AS final
# by copying from the deps stage we leave behind all cache and temporary files created during installation
COPY --from=deps /venv /venv
COPY --from=deps /app/external /app/external

WORKDIR /app
COPY src/xDiT/ci/run.hunyuanvideo.sh /app/.ci/run.hunyuanvideo.sh
COPY --from=hunyuanvideo /app/Hunyuanvideo /app/Hunyuanvideo
COPY src/flux/ci/run.flux.sh /app/.ci/run.flux.sh
COPY src/flux/ci/run.flux.kontext.sh /app/.ci/run.flux.kontext.sh
COPY src/flux/ci/run.flux2.sh /app/.ci/run.flux2.sh
COPY --from=flux /app/Flux /app/Flux
RUN cd /app/Flux && \
    pip install --no-cache-dir -r requirements.txt
COPY src/SD_3_5/ci/run.stablediffusion_3_5.sh /app/.ci/run.stablediffusion_3_5.sh
COPY --from=stablediffusion3.5 /app/StableDiffusion3.5 /app/StableDiffusion3.5
COPY src/wan_xdit/ci/run.wan2.1.sh /app/.ci/run.wan2.1.sh
COPY src/wan_xdit/ci/run.wan2.2.sh /app/.ci/run.wan2.2.sh
COPY --from=wan /app/Wan /app/Wan
RUN cd /app/Wan && \
    pip install --no-cache-dir -r requirements.txt
COPY --from=z_image /app/Z-Image /app/Z-Image
COPY src/z_image/ci/run.z_image_turbo.sh /app/.ci/run.z_image_turbo.sh
COPY .ci/run.py /app/.ci/run.py
COPY benchmark_configs/ /app/.ci/benchmark_configs/
COPY .ci/quality_check.sh /app/.ci/quality_check.sh
# use shared MIOpen databases
COPY ./data/miopen/userdb /miopen_userdb
ENV MIOPEN_USER_DB_PATH="/miopen_userdb"
# add quality references of workloads
ADD references/ /app/references/
