# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

ARG BASE_IMAGE="amdsiloai/pytorch-xdit:v26.7"
FROM ${BASE_IMAGE}

ARG VLLM_COMMIT="ad7125a" # v0.21.0
ARG SGL_COMMIT="f8f2870" # v0.5.16+
ARG SGL_REPO="https://github.com/sgl-project/sglang.git"
ARG AMDGPU_TARGET="gfx950"

WORKDIR /app/external
# Install vLLM
RUN git clone https://github.com/vllm-project/vllm.git && \
    cd vllm && \
    git reset --hard ${VLLM_COMMIT} && \
    pip3 install --no-cache-dir setuptools_scm && \
    pip3 install --no-cache-dir -r requirements/rocm.txt && \
    PYTORCH_ROCM_ARCH="gfx942;gfx950" python3 setup.py develop

# Install SGL
RUN git clone ${SGL_REPO} sglang && \
    cd sglang && \
    git checkout ${SGL_COMMIT} && \
    cd sgl-kernel && \
    AMDGPU_TARGET="$AMDGPU_TARGET" python3 setup_rocm.py install && \
    cd .. && \
    mv python/pyproject_other.toml python/pyproject.toml && \
    sed -i '/numpy/d' python/pyproject.toml && \
    sed -i '/torch/d' python/pyproject.toml && \
    sed -i '/torchvision/d' python/pyproject.toml && \
    sed -i '/transformers/d' python/pyproject.toml && \
    sed -i '/timm/d' python/pyproject.toml && \
    sed -i '/diffusers/d' python/pyproject.toml && \
    sed -i '/accelerate/d' python/pyproject.toml && \
    pip install --no-cache-dir -e "python[all_hip,diffusion]"

# Other dependencies
RUN pip3 install remote_pdb imageio && \
    pip3 uninstall torch_c_dlpack_ext -y

RUN pip3 install "transformers==5.12.1" --upgrade && \
    pip3 install "flydsl==0.2.4" --upgrade

# Envs
ENV SGLANG_TORCH_COMPILE_MODE="default"
ENV SGLANG_USE_ROCM_VAE=0
ENV SGLANG_DIFFUSION_DISABLE_SP_PAD_MASK=1 # Requires SGL PR #33855
ENV MIOPEN_DEBUG_CONV_DIRECT=0

WORKDIR /app
# Include CI
RUN rm -fr /app/.ci/*
COPY .ci/run.py /app/.ci/run.py
COPY .ci/integrations/sgld/runner.py /app/.ci/runner.py
COPY benchmark_configs/sgld/ /app/.ci/benchmark_configs/
