# Build example image with
#
# docker build -f docker/Dockerfile.cuda \
#              -t pytorch_xdit_cuda .
#
# when running from repository root.
#

# deps image arguments
ARG FLASHATTENTION_COMMIT="5d2cd3b"
ARG LONGCONTEXTATTENTION_COMMIT="2c9b712"
ARG DIFFUSERS_COMMIT="6708f5"
ARG ACCELERATE_COMMIT="b521400"
ARG XDIT_COMMIT="419fa3c"
ARG AO_COMMIT="8b72284"

ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:25.06-py3
FROM ${BASE_IMAGE} AS core

# For ImportError: libGL.so.1: cannot open shared object file on nvcr.io/nvidia/pytorch:25.06-py3
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

FROM core AS deps
ARG FLASHATTENTION_COMMIT
ARG LONGCONTEXTATTENTION_COMMIT
ARG DIFFUSERS_COMMIT
ARG ACCELERATE_COMMIT
ARG XDIT_COMMIT
ARG AO_COMMIT

# setup
WORKDIR /app/external
COPY src/patches /patches
COPY src/patches-private /patches-private
# install flash-attention
RUN pip uninstall -y flash_attn && \
    git clone https://github.com/Dao-AILab/flash-attention.git && \
    cd flash-attention && \
    git reset --hard ${FLASHATTENTION_COMMIT} && \
    (cd hopper && python setup.py install) && \
    (cd flash_attn/cute && pip install -e .)
# install yunchang
RUN git clone https://github.com/feifeibear/long-context-attention.git && \
    cd long-context-attention && \
    git reset --hard ${LONGCONTEXTATTENTION_COMMIT} && \
    git apply /patches-private/yunchang_globals.patch && \
    git apply /patches-private/yunchang_kernels.patch && \
    git apply /patches-private/yunchang_attention.patch && \
    pip install -e .
# install diffusers
RUN git clone https://github.com/huggingface/diffusers.git && \
    cd diffusers && \
    git reset --hard ${DIFFUSERS_COMMIT} && \
    pip install -e ".[torch]"
# install accelerate
RUN git clone https://github.com/huggingface/accelerate.git && \
    cd accelerate && \
    git reset --hard ${ACCELERATE_COMMIT} && \
    pip install -e .
# install xfuser
RUN git clone https://github.com/xdit-project/xDiT.git && \
    cd xDiT && \
    git reset --hard ${XDIT_COMMIT} && \
    git apply /patches/xfuser_joint_attn_processor2_0_usp.patch && \
    git apply /patches/xfuser_attention_backend.patch && \
    git apply /patches/xfuser_runtime_state.patch && \
    git apply /patches/xfuser_usp.patch && \
    pip freeze | grep numpy > constraints.txt && \
    pip install -c constraints.txt -e .
# install torchao
RUN git clone https://github.com/pytorch/ao.git && \
    cd ao && \
    git reset --hard ${AO_COMMIT} && \
    pip install -e . --no-build-isolation
# cleanup
RUN rm -fr /patches
RUN rm -fr /patches-private

FROM deps AS hunyuanvideo
WORKDIR /app/Hunyuanvideo
COPY src/xDiT/ci/README_huvideo.md /app/Hunyuanvideo/RUN.md
COPY src/xDiT/ci/video_descriptions.csv /app/Hunyuanvideo/video_descriptions.csv
COPY src/xDiT/ci/huvideo_utils.py /app/Hunyuanvideo/huvideo_utils.py
COPY src/xDiT/ci/hunyuan_video_usp_example_custom.py /app/Hunyuanvideo/run.py

FROM deps AS flux
WORKDIR /app/Flux
COPY src/flux/ci/README.md /app/Flux/RUN.md
COPY src/flux/flux_utils.py /app/Flux/flux_utils.py
COPY src/flux/flux_example.py /app/Flux/run.py
COPY src/flux/flux_usp_example.py /app/Flux/run_usp.py
COPY src/flux/requirements.txt /app/Flux/requirements.txt
COPY src/flux/cat.png /app/Flux/cat.png

FROM deps AS stablediffusion3.5
WORKDIR /app/StableDiffusion3.5
COPY src/SD_3_5/ci/README.md /app/StableDiffusion3.5/RUN.md
COPY src/SD_3_5/scripts/sd3_utils.py /app/StableDiffusion3.5/sd3_utils.py
COPY src/SD_3_5/scripts/sd3_example.py /app/StableDiffusion3.5/run.py

FROM deps AS wan
WORKDIR /app/Wan
COPY src/wan_xdit/ci/README.md /app/Wan/RUN.md
COPY src/wan_xdit/wan_utils.py /app/Wan/wan_utils.py
COPY src/wan_xdit/wan_example.py /app/Wan/run.py
COPY src/wan_xdit/assets/i2v_input.JPG /app/Wan/i2v_input.JPG
COPY src/wan_xdit/requirements.txt /app/Wan/requirements.txt

FROM deps AS z_image
WORKDIR /app/Z-Image
COPY src/z_image/ci/README.md /app/Z-Image/RUN.md
COPY src/z_image/z_image_utils.py /app/Z-Image/z_image_utils.py
COPY src/z_image/z_image_example.py /app/Z-Image/run.py

FROM deps AS hunyuanvideo_1_5
WORKDIR /app/Hunyuanvideo_1_5
COPY src/hunyuanvideo_1_5/ci/README.md /app/Hunyuanvideo_1_5/RUN.md
COPY src/hunyuanvideo_1_5/hunyuanvideo_1_5_utils.py /app/Hunyuanvideo_1_5/hunyuanvideo_1_5_utils.py
COPY src/hunyuanvideo_1_5/hunyuanvideo_1_5_example.py /app/Hunyuanvideo_1_5/run.py

FROM deps AS final

WORKDIR /app
COPY src/xDiT/ci/run.hunyuanvideo.sh /app/.ci/run.hunyuanvideo.sh
COPY --from=hunyuanvideo /app/Hunyuanvideo /app/Hunyuanvideo
COPY src/flux/ci/run.flux.sh /app/.ci/run.flux.sh
COPY src/flux/ci/run.flux.kontext.sh /app/.ci/run.flux.kontext.sh
COPY src/flux/ci/run.flux2.sh /app/.ci/run.flux2.sh
COPY --from=flux /app/Flux /app/Flux
RUN cd /app/Flux && \
    pip install --no-cache-dir -r requirements.txt
COPY src/SD_3_5/ci/run.stablediffusion_3_5.sh /app/.ci/run.stablediffusion_3_5.sh
COPY --from=stablediffusion3.5 /app/StableDiffusion3.5 /app/StableDiffusion3.5
COPY src/wan_xdit/ci/run.wan2.1.sh /app/.ci/run.wan2.1.sh
COPY src/wan_xdit/ci/run.wan2.2.sh /app/.ci/run.wan2.2.sh
COPY --from=wan /app/Wan /app/Wan
COPY --from=z_image /app/Z-Image /app/Z-Image
COPY src/z_image/ci/run.z_image_turbo.sh /app/.ci/run.z_image_turbo.sh
COPY --from=hunyuanvideo_1_5 /app/Hunyuanvideo_1_5 /app/Hunyuanvideo_1_5
COPY src/hunyuanvideo_1_5/ci/run.hunyuanvideo_1_5.sh /app/.ci/run.hunyuanvideo_1_5.sh
RUN cd /app/Wan && \
    pip install --no-cache-dir -r requirements.txt
COPY .ci/run.py /app/.ci/run.py
COPY benchmark_configs/ /app/.ci/benchmark_configs/
# apex causes rms_forward_affine crash in SD3.5 and numpy>2 a runtime error in Hunyuanvideo
RUN pip uninstall -y apex && pip install "numpy<2"
