# Build example image with
#
# docker build -f docker/Dockerfile.cuda \
#              -t pytorch_xdit_cuda .
#
# when running from repository root.
#

# deps image arguments
ARG GPU_ARCH=""
ARG FLASHATTENTION_COMMIT="5d2cd3b"
ARG LONGCONTEXTATTENTION_COMMIT="2c9b712"
ARG DIFFUSERS_COMMIT="40528e9"
ARG ACCELERATE_COMMIT="b521400"
ARG XDIT_COMMIT="ccba9d5"
ARG AO_COMMIT="8b72284"

ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:25.06-py3
FROM ${BASE_IMAGE} AS core

# For ImportError: libGL.so.1: cannot open shared object file on nvcr.io/nvidia/pytorch:25.06-py3
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

FROM core AS deps
ARG GPU_ARCH
ARG FLASHATTENTION_COMMIT
ARG LONGCONTEXTATTENTION_COMMIT
ARG DIFFUSERS_COMMIT
ARG ACCELERATE_COMMIT
ARG XDIT_COMMIT
ARG AO_COMMIT

# setup
WORKDIR /app/external
COPY src/patches /patches
COPY src/patches-private /patches-private
# install flash-attention
RUN if [[ -n "$GPU_ARCH" ]]; then \
        pip uninstall -y flash-attn; \
        git clone https://github.com/Dao-AILab/flash-attention.git && \
        cd flash-attention && \
        git reset --hard ${FLASHATTENTION_COMMIT}; \
        if [ "$GPU_ARCH" = "hopper" ]; then \
            cd hopper && \
            python setup.py install; \
        elif [ "$GPU_ARCH" = "blackwell" ]; then \
            cd flash_attn/cute && \
            pip install -e .; \
        else \
            echo "invalid GPU_ARCH ${GPU_ARCH}"; \
        fi \
    fi
# install yunchang
RUN git clone https://github.com/feifeibear/long-context-attention.git && \
    cd long-context-attention && \
    git reset --hard ${LONGCONTEXTATTENTION_COMMIT} && \
    git apply /patches-private/yunchang_globals.patch && \
    git apply /patches-private/yunchang_kernels.patch && \
    git apply /patches-private/yunchang_attention.patch && \
    pip install -e .
# install diffusers
RUN git clone https://github.com/huggingface/diffusers.git && \
    cd diffusers && \
    git reset --hard ${DIFFUSERS_COMMIT} && \
    pip install -e ".[torch]"
# install accelerate
RUN git clone https://github.com/huggingface/accelerate.git && \
    cd accelerate && \
    git reset --hard ${ACCELERATE_COMMIT} && \
    pip install -e .
# install xfuser
RUN git clone https://github.com/xdit-project/xDiT.git && \
    cd xDiT && \
    git reset --hard ${XDIT_COMMIT} && \
    git apply /patches-private/xfuser_envs.patch && \
    git apply /patches-private/xfuser_attention_processor.patch && \
    git apply /patches-private/xfuser_base_pipeline.patch && \
    git apply /patches-private/xfuser_ring_flash_attn.patch && \
    pip freeze | grep numpy > constraints.txt && \
    pip install -c constraints.txt -e .
# install torchao
RUN git clone https://github.com/pytorch/ao.git && \
    cd ao && \
    git reset --hard ${AO_COMMIT} && \
    pip install -e . --no-build-isolation
# cleanup
RUN rm -fr /patches
RUN rm -fr /patches-private

FROM deps AS hunyuanvideo

WORKDIR /app/Hunyuanvideo
COPY src/xDiT/ci/README_huvideo.md /app/Hunyuanvideo/RUN.md
COPY src/xDiT/ci/video_descriptions.csv /app/Hunyuanvideo/video_descriptions.csv
COPY src/xDiT/ci/huvideo_utils.py /app/Hunyuanvideo/huvideo_utils.py
COPY src/xDiT/ci/hunyuan_video_usp_example_custom.py /app/Hunyuanvideo/run.py

FROM deps AS flux
WORKDIR /app/Flux
COPY src/flux/ci/README.md /app/Flux/RUN.md
COPY src/flux/flux_utils.py /app/Flux/flux_utils.py
COPY src/flux/flux_example.py /app/Flux/run.py
COPY src/flux/flux_usp_example.py /app/Flux/run_usp.py
COPY src/flux/requirements.txt /app/Flux/requirements.txt

FROM deps AS wan
WORKDIR /app/Wan
COPY src/wan_xdit/ci/README.md /app/Wan/RUN.md
COPY src/wan_xdit/wan_utils.py /app/Wan/wan_utils.py
COPY src/wan_xdit/wan_example.py /app/Wan/run.py
COPY src/wan_xdit/assets/i2v_input.JPG /app/Wan/i2v_input.JPG
COPY src/wan_xdit/requirements.txt /app/Wan/requirements.txt


FROM deps AS final

WORKDIR /app
COPY src/xDiT/ci/run.hunyuanvideo.sh /app/.ci/run.hunyuanvideo.sh
COPY --from=hunyuanvideo /app/Hunyuanvideo /app/Hunyuanvideo
COPY src/flux/ci/run.flux.sh /app/.ci/run.flux.sh
COPY --from=flux /app/Flux /app/Flux
RUN cd /app/Flux && \
    pip install --no-cache-dir -r requirements.txt
COPY src/wan_xdit/ci/run.wan2.1.sh /app/.ci/run.wan2.1.sh
COPY src/wan_xdit/ci/run.wan2.2.sh /app/.ci/run.wan2.2.sh
COPY --from=wan /app/Wan /app/Wan
RUN cd /app/Wan && \
    pip install --no-cache-dir -r requirements.txt
COPY .ci/run.sh /app/.ci/run.sh
