ARG BASE_IMAGE="amdsiloai/pytorch-xdit:v26.4"
FROM ${BASE_IMAGE}

ARG VLLM_COMMIT="2d5be1d" # v0.16.0
ARG SGL_COMMIT="9b0c470" # v0.5.10rc0
ARG AMDGPU_TARGET="gfx942"

WORKDIR /app/external
# Install vLLM
RUN git clone https://github.com/vllm-project/vllm.git && \
    cd vllm && \
    git reset --hard ${VLLM_COMMIT} && \
    pip3 install --no-cache-dir setuptools_scm && \
    pip3 install --no-cache-dir -r requirements/rocm.txt && \
    PYTORCH_ROCM_ARCH="gfx942;gfx950" python3 setup.py develop

# Install SGL
RUN git clone https://github.com/sgl-project/sglang.git && \
    cd sglang && \
    git reset --hard ${SGL_COMMIT} && \
    cd sgl-kernel && \
    AMDGPU_TARGET="$AMDGPU_TARGET" python3 setup_rocm.py install && \
    cd .. && \
    mv python/pyproject_other.toml python/pyproject.toml && \
    sed -i '/numpy/d' python/pyproject.toml && \
    sed -i '/torch/d' python/pyproject.toml && \
    sed -i '/torchvision/d' python/pyproject.toml && \
    sed -i '/transformers/d' python/pyproject.toml && \
    sed -i '/timm/d' python/pyproject.toml && \
    sed -i '/diffusers/d' python/pyproject.toml && \
    sed -i '/accelerate/d' python/pyproject.toml && \
    pip install --no-cache-dir -e "python[all_hip,diffusion]"

# Other dependencies
RUN pip3 install remote_pdb imageio

# Envs
ENV SGLANG_TORCH_COMPILE_MODE="default"
ENV MIOPEN_DEBUG_CONV_DIRECT=0

WORKDIR /app
# Include CI
RUN rm -fr /app/.ci/*
COPY .ci/run.py /app/.ci/run.py
COPY .ci/integrations/sgld/runner.py /app/.ci/runner.py
COPY benchmark_configs/sgld/ /app/.ci/benchmark_configs/
