# Build example (run from the diffusion-models-inference repo root):
#
#   docker build \
#     -f docker/Dockerfile.vllm_omni \
#     -t vllm-omni:test \
#     .
#

ARG BASE_IMAGE="amdsiloai/pytorch-private:xdit-2.13-20260803"

FROM scratch AS patches
COPY ./patches /patches

FROM ${BASE_IMAGE}

ARG VLLM_REPO=https://github.com/vllm-project/vllm.git
ARG VLLM_COMMIT="4bdc8a7" # v0.27.0 release

ARG VLLM_OMNI_REPO=https://github.com/vllm-project/vllm-omni.git
ARG VLLM_OMNI_COMMIT="02069a5" # v0.27.0+ release

ARG FLASH_ATTENTION_REPO=https://github.com/Dao-AILab/flash-attention.git
ARG FLASH_ATTENTION_COMMIT="0e60e394"

# Builds FA with Triton backend (https://github.com/ROCm/flash-attention#triton-backend)
ENV FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE"

ENV VLLM_TARGET_DEVICE=rocm
ENV VLLM_OMNI_TARGET_DEVICE=rocm

WORKDIR /app/external

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        pkg-config \
        libdrm-dev \
        libopenmpi3 \
    && rm -rf /var/lib/apt/lists/*

# Install flash-attention.
RUN git clone ${FLASH_ATTENTION_REPO} && \
    cd flash-attention && \
    git reset --hard ${FLASH_ATTENTION_COMMIT} && \
    MAX_JOBS=$(($(nproc) / 2)) pip install --no-build-isolation -e .

# Install vLLM
RUN git clone ${VLLM_REPO} && \
    cd vllm && \
    git reset --hard ${VLLM_COMMIT} && \
    pip3 install --no-cache-dir setuptools_scm && \
    pip3 install --no-cache-dir -r requirements/rocm.txt && \
    PYTORCH_ROCM_ARCH="gfx942;gfx950" python3 setup.py develop

# Install vLLM-Omni
RUN git clone ${VLLM_OMNI_REPO} /app/vllm-omni && \
    cd /app/vllm-omni && \
    git reset --hard ${VLLM_OMNI_COMMIT}

RUN cd /app/vllm-omni && \
    VLLM_OMNI_TARGET_DEVICE=rocm pip install -e .

WORKDIR /app
# Copy assets
COPY assets/data /app/data
# Include CI
RUN rm -fr /app/.ci/*
COPY .ci/run.py /app/.ci/run.py
COPY .ci/integrations/vllm_omni/runner.py /app/.ci/runner.py
COPY .ci/integrations/vllm_omni/online_runner.py /app/.ci/online_runner.py
COPY benchmark_configs/omni/ /app/.ci/benchmark_configs/
