# libkineto.conf
#
# This file overrides configuration values for Kineto profiling library used by PyTorch profiler.
# Possible configuration values to modify are listed in https://github.com/pytorch/kineto/blob/main/libkineto/src/Config.cpp
#
# Usage:
# Save this file to a desired location, for example /app/libkineto.conf
# When running an application that uses Kineto, set the environment variable KINETO_CONFIG="/app/libkineto.conf"

# Increase the maximum number of GPU events logged by RocTracer on AMD GPUs.
ROCTRACER_MAX_EVENTS=10000000