name: Build xDiT Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag. Short commit SHA will be used by default. Untuned image will receive an additional -temp suffix."
        required: false
        default: ""
      runner:
        description: "Runner label"
        required: false
        default: "build-only"
jobs:
  build-xdit-core:
    name: Build xDiT core image
    runs-on: ${{ github.event.inputs.runner || 'build-only' }}
    timeout-minutes: 540
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: false
      - name: Get commit SHA
        id: short_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_OAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check Docker
        run: docker info
      - name: Build core image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.ci
          context: .
          target: core
          push: true
          load: false
          tags: amdsiloai/pytorch-xdit-core:${{ github.event.inputs.tag || steps.short_sha.outputs.sha }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=min
      - name: Build untuned image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.ci
          context: .
          push: true
          load: false
          tags: amdsiloai/pytorch-xdit-staging:${{ github.event.inputs.tag || steps.short_sha.outputs.sha }}-temp
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: type=local,src=/tmp/.buildx-cache